{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception(\"oops\")\nE       Exception: oops\n\ntestdemo\\python-allure使用.py:13: Exception"}, "start": 1635060717643, "stop": 1635060717644, "uuid": "14201645-672b-4c83-96ef-c7fd9dd79fc8", "historyId": "2dd18f3719921a30641489bd07b18c5e", "testCaseId": "ab5012f7bf320750b2bdbadf1d2ca173", "fullName": "testdemo.python-allure使用#test_broken", "labels": [{"name": "parentSuite", "value": "testdemo"}, {"name": "suite", "value": "python-allure使用"}, {"name": "host", "value": "010A05050057"}, {"name": "thread", "value": "2256-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testdemo.python-allure使用"}]}