{"name": "test_attach_photo", "status": "broken", "statusDetails": {"message": "OSError: [Errno 22] Invalid argument: 'D:\\\\PycharmProjects\\\\PyTest\\\\photo\\x04.png'", "trace": "def test_attach_photo():\n>       allure.attach.file(\"D:\\PycharmProjects\\PyTest\\photo\\4.png\",name=\"这是一个图片\",attachment_type=allure.attachment_type.PNG)\n\ntestdemo\\python-allure-attach.py:10: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nd:\\python36\\lib\\site-packages\\allure_commons\\_allure.py:182: in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\nd:\\python36\\lib\\site-packages\\pluggy\\_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\nd:\\python36\\lib\\site-packages\\pluggy\\_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\nd:\\python36\\lib\\site-packages\\allure_pytest\\listener.py:226: in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\nd:\\python36\\lib\\site-packages\\allure_commons\\reporter.py:114: in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\nd:\\python36\\lib\\site-packages\\pluggy\\_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\nd:\\python36\\lib\\site-packages\\pluggy\\_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\nd:\\python36\\lib\\site-packages\\allure_commons\\logger.py:53: in report_attached_file\n    shutil.copy2(source, destination)\nd:\\python36\\lib\\shutil.py:263: in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nsrc = 'D:\\\\PycharmProjects\\\\PyTest\\\\photo\\x04.png'\ndst = 'D:\\\\PycharmProjects\\\\PyTest\\\\result\\\\allure3\\\\41ef5c2e-e633-4f8c-8647-6ccf21031bed-attachment.png'\n\n    def copyfile(src, dst, *, follow_symlinks=True):\n        \"\"\"Copy data from src to dst.\n    \n        If follow_symlinks is not set and src is a symbolic link, a new\n        symlink will be created instead of copying the file it points to.\n    \n        \"\"\"\n        if _samefile(src, dst):\n            raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\n    \n        for fn in [src, dst]:\n            try:\n                st = os.stat(fn)\n            except OSError:\n                # File most likely does not exist\n                pass\n            else:\n                # XXX What about other special files? (sockets, devices...)\n                if stat.S_ISFIFO(st.st_mode):\n                    raise SpecialFileError(\"`%s` is a named pipe\" % fn)\n    \n        if not follow_symlinks and os.path.islink(src):\n            os.symlink(os.readlink(src), dst)\n        else:\n>           with open(src, 'rb') as fsrc:\nE           OSError: [Errno 22] Invalid argument: 'D:\\\\PycharmProjects\\\\PyTest\\\\photo\\x04.png'\n\nd:\\python36\\lib\\shutil.py:120: OSError"}, "attachments": [{"name": "这是一个图片", "source": "41ef5c2e-e633-4f8c-8647-6ccf21031bed-attachment.png", "type": "image/png"}], "start": 1635075672272, "stop": 1635075672273, "uuid": "338db0ab-b5d0-4447-8f9a-d3d4174ec7ca", "historyId": "8b1f5e8701a78f7e41a354ee88dc959d", "testCaseId": "05feacbb1ee4778eea69d54f7d3387bd", "fullName": "testdemo.python-allure-attach#test_attach_photo", "labels": [{"name": "parentSuite", "value": "testdemo"}, {"name": "suite", "value": "python-allure-attach"}, {"name": "host", "value": "010A05050057"}, {"name": "thread", "value": "16412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testdemo.python-allure-attach"}]}